* tf.keras.preprocessing.text.text_to_word_sequence(
    input_text,
    filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
    lower=True,
    split=' '
)

In [2]:
import numpy
import tensorflow as tf
from numpy import array
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Embedding

# 주어진 문장을 '단어'로 토큰화하기
# 케라스의 텍스트 전처리와 관련한 함수중 text_to_word_sequence 함수를 불러옴
from tensorflow.keras.preprocessing.text import text_to_word_sequence

# 전처리할 텍스트를 정합니다.
text = '해보지 않으면 해낼 수 없다'

# 해당 텍스트를 토큰화 합니다. 
result = text_to_word_sequence(text)
print ('\n 원문 : \n', text)
print ('\n 토큰화 : \n', result)

2023-10-19 10:53:47.080148: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.



 원문 : 
 해보지 않으면 해낼 수 없다

 토큰화 : 
 ['해보지', '않으면', '해낼', '수', '없다']


In [3]:
# 단어 빈도수 세기
# 전처리 하려는 세개의 문장을 정합니다. 
docs = ['먼저 텍스트의 각 단어를 나누어 텍스트의 단위를 토큰화 합니다.',
        '텍스트의 단어로 토큰화 해야 딥러닝에서 인식됩니다.',
        '토큰화 한 결과는 딥러닝에서 사용할 수 있습니다.']

In [4]:
# 토큰화 함수를 이용해 전처리 하는 과정입니다.
token = Tokenizer() # 토큰화 함수 지정
token.fit_on_texts(docs) # 토큰화 함수에 문장 적용

# 단어의 빈도수를 계산한 결과를 각 옵션에 맞추어 출력합니다. 
print("\n단어 카운트:\n", token.word_counts)
# Tokenizer()의 word_counts 함수는 순서를 기억하는 OrderedDict클래스를 사용합니다.

# 출력되는 순서는 랜덤입니다.
print("\n문장 카운트 :", token.document_count)
print("\n각 단어가 몇 개의 문장에 포함되어 있는가:\n", token.word_docs)
print("\n각 단어에 매겨진 인덱스 값: \n", token.word_index)


단어 카운트:
 OrderedDict([('먼저', 1), ('텍스트의', 3), ('각', 1), ('단어를', 1), ('나누어', 1), ('단위를', 1), ('토큰화', 3), ('합니다', 1), ('단어로', 1), ('해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])

문장 카운트 : 3

각 단어가 몇 개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'각': 1, '나누어': 1, '먼저': 1, '단어를': 1, '텍스트의': 2, '합니다': 1, '단위를': 1, '토큰화': 3, '인식됩니다': 1, '단어로': 1, '딥러닝에서': 2, '해야': 1, '수': 1, '사용할': 1, '있습니다': 1, '결과는': 1, '한': 1})

각 단어에 매겨진 인덱스 값: 
 {'텍스트의': 1, '토큰화': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '나누어': 7, '단위를': 8, '합니다': 9, '단어로': 10, '해야': 11, '인식됩니다': 12, '한': 13, '결과는': 14, '사용할': 15, '수': 16, '있습니다': 17}


* tf.keras.preprocessing.text.Tokenizer(
    num_words=None,
    filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
    lower=True,
    split=' ',
    char_level=False,
    oov_token=None,
    analyzer=None,
    **kwargs
)

* num_words : 한계를 줌 -> 단어의 빈도수에 따라 제거. 즉, 많이 사용하지 않은 단어는 삭제

In [5]:
# 문장의 원-핫 인코딩
from tensorflow.keras.preprocessing.text import Tokenizer

text = "오랫동안 꿈꾸는 저는 그 꿈을 닮아간다"

token = Tokenizer()
token.fit_on_texts([text])
print('문장의 토큰화 :', token.word_index)

# 각 단어를 숫자화 
x = token.texts_to_sequences([text])
print('문장의 숫자화:', x)

# 원-핫 인코딩 방식으로 표현하면
from tensorflow.keras.utils import to_categorical

word_size = len(token.word_index) + 1
x = to_categorical(x, num_classes = word_size)
print('문장의 원-핫 인코딩:\n', x)

문장의 토큰화 : {'오랫동안': 1, '꿈꾸는': 2, '저는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}
문장의 숫자화: [[1, 2, 3, 4, 5, 6]]
문장의 원-핫 인코딩:
 [[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


In [12]:
# 텍스트 리뷰 자료 지정
docs = ['너무 재밌네요', '최고예요', '참 잘 만든 영화예요','추천하고 싶은 영화입니다.','한 번 더 보고싶네요', '글쎄요','별로예요','생각보다 지루하네요','연기가 어색해요','재미없어요']

# 긍정리뷰는 1, 부정 리뷰는 0으로 클래스 지정
labels = array([1,1,1,1,1,0,0,0,0,0])

# 토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index) # 토큰화 된 결과를 출력해 확인

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한': 11, '번': 12, '더': 13, '보고싶네요': 14, '글쎄요': 15, '별로예요': 16, '생각보다': 17, '지루하네요': 18, '연기가': 19, '어색해요': 20, '재미없어요': 21}


In [13]:
x = token.texts_to_sequences(docs)
print(x)

[[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13, 14], [15], [16], [17, 18], [19, 20], [21]]


In [14]:
padded_x = pad_sequences(x,4)
print("\n패딩 결과:\n", padded_x)


패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [11 12 13 14]
 [ 0  0  0 15]
 [ 0  0  0 16]
 [ 0  0 17 18]
 [ 0  0 19 20]
 [ 0  0  0 21]]


In [15]:
word_size = len(token.word_index) +1

In [16]:
Embedding(word_size, 8, input_length=4)

In [17]:
# 단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과를 출력
model = Sequential()
model.add(Embedding(word_size,8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x,labels,epochs=20)
print("\n Accuracy: %.4f" % (model.evaluate(padded_x,labels)[1]))

Epoch 1/20
1/1 [==============================] - 1s 600ms/step - loss: 0.6944 - accuracy: 0.4000
Epoch 2/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6922 - accuracy: 0.6000
Epoch 3/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6900 - accuracy: 0.7000
Epoch 4/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6878 - accuracy: 0.7000
Epoch 5/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6856 - accuracy: 0.7000
Epoch 6/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6834 - accuracy: 0.7000
Epoch 7/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6812 - accuracy: 0.8000
Epoch 8/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6791 - accuracy: 0.9000
Epoch 9/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6769 - accuracy: 0.9000
Epoch 10/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6747 - accuracy: 0.9000
Epoch 11/20
1/1 [====================

In [18]:
word = "너무 더 보고싶네요"
X_test = token.texts_to_sequences([word])
print(X_test)

[[1, 13, 14]]


In [19]:
padded_x_test = pad_sequences(X_test, 4)
print('\n패딩 결과 :\n', padded_x_test)


패딩 결과 :
 [[ 0  1 13 14]]


1/1 [==============================] - 0s 125ms/step


array([[0.539925]], dtype=float32)